# Generated by Django 5.1.2 on 2025-01-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='news_app.puser')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='news_app.puser')),
            ],
        ),
    ]
