# Generated by Django 5.1.2 on 2025-01-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='puser',
            name='subscriptions',
            field=models.ManyToManyField(through='accounts.Subscriptions', to='news_app.puser'),
        ),
    ]
