# Generated by Django 5.1.2 on 2025-01-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_puser_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_en_us',
            field=models.CharField(help_text='Название Категории', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(help_text='Название Категории', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Название Категории', max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en_us', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='news_app.category', verbose_name='This is the help text')),
            ],
        ),
    ]
